# Generated by Django 3.0.6 on 2020-05-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category', max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-05-18')),
                ('due_date', models.DateField(default='2020-05-18')),
                ('category', models.ForeignKey(default='General', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
